Repository AY2021S1-CS2103T-W11-4/tp, pull requests merged in 2020-10, with the labels that each got.

#60 Add IcNumber class
  src/main/java/seedu/address/model/patient/IcNumber.java
  src/main/java/seedu/address/model/patient/Phone.java
  src/test/java/seedu/address/model/patient/IcNumberTest.java
Labels: priority.High

#61 Add profile picture
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddProfilePictureCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddProfilePictureCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CliniCalParser.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/ProfilePicture.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/java/seedu/address/ui/PatientListPanel.java
  src/main/resources/view/PatientListCard.fxml
  src/test/data/JsonCliniCalStorageTest/invalidAndValidPatientCliniCal.json
  src/test/data/JsonSerializableCliniCalTest/duplicatePatientCliniCal.json
  src/test/data/JsonSerializableCliniCalTest/typicalPatientsCliniCal.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddProfilePictureCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/HistoryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddProfilePictureCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CliniCalParserTest.java
  src/test/java/seedu/address/model/patient/ProfilePictureTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: enhancement

#67 Adds navigation keys to access past commands
  src/main/java/seedu/address/model/history/CommandHistory.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/model/history/CommandHistoryTest.java
Labels: enhancement

#69 Update UG on drag and drop functionality for profile picture
  docs/UserGuide.md
Labels: documentation

#68 Add undo redo command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddProfilePictureCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/CliniCalParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedCliniCal.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/CliniCalParserTest.java
  src/test/java/seedu/address/model/VersionedCliniCalTest.java
Labels: enhancement

#75 Update DG Headings and Subheadings
  docs/DeveloperGuide.md
Labels: documentation

#72 Update UG (Arrow Keys)
  docs/UserGuide.md
Labels: documentation

#77 Fix bug in CommandBox
  src/main/java/seedu/address/ui/CommandBox.java
Labels: bug

#78 Fix build error
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: bug

#79 Update user guide and UI mockup
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/model/visit/Visit.java
  src/main/java/seedu/address/model/visit/VisitHistory.java
Labels: documentation

#83 Update DG for profile picture
  docs/DeveloperGuide.md
  docs/diagrams/AddProfilePictureSequenceDiagram.puml
  docs/images/AddProfilePictureSequenceDiagram.png
Labels: documentation

#96 Update DG to reflect new patient fields
  README.md
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
Labels: documentation

#95 Add Find IC functionality
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/patient/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/model/patient/NameContainsKeywordsPredicateTest.java
Labels: enhancement

#109 Fix N/A field bug
  ModelClassDiagram.png
  src/main/java/seedu/address/model/patient/Address.java
  src/main/java/seedu/address/model/patient/BloodType.java
  src/main/java/seedu/address/model/patient/Email.java
  src/main/java/seedu/address/model/patient/Sex.java
  src/test/java/seedu/address/model/patient/AddressTest.java
  src/test/java/seedu/address/model/patient/BloodTypeTest.java
  src/test/java/seedu/address/model/patient/EmailTest.java
  src/test/java/seedu/address/model/patient/SexTest.java
Labels: bug

#120 Add example images to UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addExample.png
  docs/images/addProfileExample.png
  docs/images/clearExample.png
  docs/images/clearHistoryExample.png
  docs/images/colorTagExample.png
  docs/images/deleteExample.png
  docs/images/editExample.png
  docs/images/findExample.png
  docs/images/helpMessage.png
  docs/images/historyExample.png
  docs/images/listExample.png
  docs/images/redoExample.png
  docs/images/undoExample.png
Labels: documentation

#138 Add add/delete appointment commands and parsers
  docs/diagrams/AddProfilePictureSequenceDiagram.puml
  docs/images/AddProfilePictureSequenceDiagram.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointment/AppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointment/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CliniCalParser.java
  src/main/java/seedu/address/logic/parser/appointment/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointment/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedCliniCal.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentDateTime.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
Labels: enhancement

#140 Improve UG/DG based on peer reviews
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#145 Minor fix for UG
  docs/UserGuide.md
Labels: documentation

#154 Implement edit for duration
  src/main/java/seedu/address/logic/commands/appointment/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/appointment/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointment/EditAppointmentCommandParser.java
  src/main/java/seedu/address/model/appointment/AppointmentDateTime.java
  src/main/java/seedu/address/model/appointment/ReadOnlyAppointments.java
  src/main/java/seedu/address/model/appointment/ReadOnlyVEvents.java
Labels: enhancement

#161 Update UG with Add/Delete Appointment features
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#165 Update UG regarding EditAppointmentCommand
  README.md
  docs/UserGuide.md
Labels: documentation

#172 Replace Ui mockup image
  ModelClassDiagram.png
  docs/images/Ui.png
Labels: documentation

#173 Fix various bugs with undo/redo, addvisit and reorganized parts of UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddProfilePictureCommand.java
  src/main/java/seedu/address/logic/commands/AddVisitCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteVisitCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SaveVisitCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointment/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointment/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddVisitCommandParser.java
  src/main/java/seedu/address/logic/parser/CliniCalParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/visit/VisitHistory.java
  src/main/java/seedu/address/ui/VisitFormWindow.java
  src/main/resources/view/ProfileVisitCard.fxml
Labels: bug, documentation

#177 Rename app to appt, replace eg in UG to match screenshots and add screenshots for appt features
  docs/UserGuide.md
  docs/images/DeleteApptExample.png
  docs/images/addApptExample.png
  docs/images/editApptExample.png
  src/main/java/seedu/address/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointment/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointment/EditAppointmentCommand.java
Labels: documentation

#176 Fix bug and Add test for EditAppointmentCommandParser
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/appointment/EditAppointmentCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/appointment/EditAppointmentCommandParserTest.java
Labels: bug
